spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service-routing
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**
          - id: customer-service-routing
            uri: lb://customer-service
            predicates:
              - Path=/api/v1/customers/**
              - Path=/api/v1/individualcustomers/**
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
server:
  port: 8080
