apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  ports:
    - port: 8001
  selector:
    app: config-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: innova-config-server2
          ports:
            - containerPort: 8001