spring:
  application:
    name: order-service
  cloud:
    config:
      uri: ${configurl}
      profile: dev
  config:
    import: configserver:${configurl}
server:
  port: 8085
configurl: http://localhost:8001